--VMERCHTOTAL AND VSUMOFSALEPRICE ALREADY EXIST

CREATE VIEW VSALETABLE AS
SELECT SaleID, CustomerID
FROM PET..Sale
GROUP BY SaleID,CustomerID;

CREATE VIEW VTOTALMERCHSALES AS
SELECT ST.CustomerID, SUM(T.MerchTotal) AS TOTALMERCHORDERS  
FROM VMERCHTOTAL T INNER JOIN VSALETABLE ST ON T.SaleID = ST.SaleID
GROUP BY ST.CustomerID

CREATE VIEW VTOTALANIMALSALES AS
SELECT ST.CustomerID, SUM(SSP.SumOfSalePrice) AS TOTALANIMALSALES 
FROM VSUMSALEPRICE SSP INNER JOIN VSALETABLE ST ON SSP.SaleID=ST.SaleID 
GROUP BY CustomerID


SELECT TOP 1 C.CustomerID, C.LastName, C.FirstName, TM.TOTALMERCHORDERS, TS.TOTALANIMALSALES, (TM.TOTALMERCHORDERS+TS.TOTALANIMALSALES) AS GRANDTOTAL
FROM PET..Customer C INNER JOIN VTOTALANIMALSALES TS ON TS.CustomerID=C.CustomerID INNER JOIN VTOTALMERCHSALES TM ON C.CustomerID=TM.CustomerID